export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';
export const FETCH_ARTIST_ERROR = 'FETCH_ARTIST_ERROR';
export const CHANGE_ARTIST_VIEW = 'CHANGE_ARTIST_VIEW';
export const FETCH_RELATED_ARTISTS_REQUEST = 'FETCH_RELATED_ARTISTS_REQUEST';
export const FETCH_RELATED_ARTISTS_SUCCESS = 'FETCH_RELATED_ARTISTS_SUCCESS';
export const FETCH_RELATED_ARTISTS_ERROR = 'FETCH_RELATED_ARTISTS_ERROR';