export const SEARCH_ARTIST_REQUEST = 'SEARCH_ARTIST_REQUEST';
export const SEARCH_ARTIST_SUCCESS = 'SEARCH_ARTIST_SUCCESS';
export const SEARCH_ARTIST_ERROR = 'SEARCH_ARTIST_ERROR';
export const CLEAR_SEARCH_RESULTS = 'EXPIRE_SEARCH_RESULTS';
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const CHANGE_SEARCH_VIEW = 'CHANGE_SEARCH_VIEW';