export const SEARCH_ARTIST_REQUEST = 'SEARCH_ARTIST_REQUEST';
export const SEARCH_ARTIST_SUCCESS = 'SEARCH_ARTIST_SUCCESS';
export const SEARCH_ARTIST_ERROR = 'SEARCH_ARTIST_ERROR';
export const EXPIRE_SEARCH_RESULTS = 'EXPIRE_SEARCH_RESULTS';