export const FETCH_NEW_RELEASES_REQUEST = 'FETCH_NEW_RELEASES_REQUEST';
export const FETCH_NEW_RELEASES_SUCCESS = 'FETCH_NEW_RELEASES_SUCCESS';
export const FETCH_NEW_RELEASES_ERROR = 'FETCH_NEW_RELEASES_ERROR';